### ISSUE TITLE
Implement == compilation

### ISSUE THREAD

**Issue by MrMystery10-del** [MrMystery10-del/Slirik#14]
We do already compile `<` and `>` but still not compile `==`, the interpretation of it is already done. So there are no changes in the VM needed just the Compiler

**Comment by shivamxsurya** [comment]
i want to work on it. can you assign

**Comment by MrMystery10-del** [comment]
Of course, assigned you! @shivamxsurya

**Comment by MrMystery10-del** [comment]
@shivamxsurya Any progress?

**Comment by MrMystery10-del** [comment]
Done!
