### ISSUE TITLE
The interpreter is slow at executing big while loops

### ISSUE THREAD

**Issue by MrMystery10-del** [MrMystery10-del/Slirik#4]
The problem is that on each iteration it creates a new Statement object, instead it should just work with reference of the statement queue which would increace the performance significant

**Comment by anxbt** [comment]
in order to fix the bug,on what file i should make changes to.Plss help me out its my first open source contribution

**Comment by MrMystery10-del** [comment]
I dont think that thats a good issue for a new contributer, but i can still explain in case u good with Rust. As you see under main.rs every statement of the queue gets executed with the executor module. before it gets to execution it copies the statement and use that as argument for the executor. You would need to use only a reference as argument and do some changes to work with just a reference, which would increace teh performance by a lot. So since i only see that you have Java experience in your profile you should look into issues labeled with `compiler` thats where u can code with Java instead of Rust @anxbt

**Comment by MrMystery10-del** [comment]
Also the struct should take just references from the statement queue

**Comment by MrMystery10-del** [comment]
A very easy issue for you would be https://github.com/MrMystery10-del/Slirik/issues/16 where u just need to add documentation. If you want to code you could do that issue https://github.com/MrMystery10-del/Slirik/issues/8 its quiet challanging but im sure that this is possible for you. If you want more information about the issue just ask in the issues chat of the issue u want. @anxbt

**Comment by MrMystery10-del** [comment]
Done that
