### ISSUE TITLE
Implement '#' x root of y

### ISSUE THREAD

**Issue by MrMystery10-del** [MrMystery10-del/Slirik#7]
As already created x to the power of y using '^'
There is still a lake at x root of y implementation

**Comment by MrMystery10-del** [comment]
Not really, sqrt stands for square root, but there are also other roots like cubic(3) quadro(4) ... which is represented by x. 
![radical_image_1](https://user-images.githubusercontent.com/69641472/234880989-8e0e555c-16c6-4205-9720-b3a260bb357a.png)

**Comment by MrMystery10-del** [comment]
x stand for the root index and y for the radicand

**Comment by gautham2k3** [comment]
okay i get it now

**Comment by GREEDnim** [comment]
if we had power, we can simply do pow(y,1/x) ?

**Comment by MrMystery10-del** [comment]
Done!
